name: LetTutor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Create Web Release (Milestone 1)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          cache: gradle
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: "3.13.9"
          cache: true 
      - name: Install dependencies
        run: flutter pub get
      - name: Start Web Release build
        run: flutter build web --release
      - name: Upload Web Build Files
        uses: actions/upload-artifact@v1
        with:
          name: web-release
          path: ./build/web
  deploy: 
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v1
      with:
        name: web-release

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v1
      with:
        github_token: ${{ secrets.SECRET_TOKEN }}
        publish_dir: ./
